### ISSUE TITLE
fedora_install.sh scriptinde sorun

### ISSUE THREAD

**Issue by FakeFBI** [leviathan-framework/leviathan#10]
Sizin blogunuzu uzun süredir takip ediyorum, bu yeni aracı çıkardığınızı gördüm. Kullandığım dağıtım Fedora. "sh fedora_install.sh" komutunu verdiğimde scriptin "requirements.txt" dosyasını bulamadığını gördüm:
`Could not open requirements file: [Errno 2] Böyle bir dosya ya da dizin yok: 'requirements.txt'`
Bunun çözümü için requirements.txt dosyasını scripts klasörünün içine almanızı öneriyorum.

**Comment by utkusen** [comment]
merhaba. scripti lütfen ana dizinden şu şekilde çalıştırın: `bash scripts/fedora_install.sh`

**Comment by FakeFBI** [comment]
Sorunu hallettim ancak readme yi okumamıştım. Gene de teşekkürler.
