### ISSUE TITLE
Cannot communicate with Shodan.io

### ISSUE THREAD

**Issue by mother2110** [leviathan-framework/leviathan#11]
Enter Country Code:

    (Examples:TR,RU,USA,IT)
    
>>tr

    Enter Protocol 

    (Examples:ssh, ftp, telnet, smb, rdp, mysql):
    
>>ssh
Extracting IPs for following query: country:tr port:22
Please wait..
Cannot communicate with Shodan.io

I have entered the shodan api.

**Comment by utkusen** [comment]
1)Make sure that your Shodan API key is correct
2)Restart the program after entering the shodan key
3)Make sure that your Shodan API has limit

**Comment by mother2110** [comment]
3)Make sure that your Shodan API has limit

Can you explain how to do this?

**Comment by mother2110** [comment]
![image](https://user-images.githubusercontent.com/17184373/26981078-eca00784-4ce8-11e7-8b5d-17bc57a07b69.png)

**Comment by utkusen** [comment]
login to your account at shodan.io, navigate to: https://account.shodan.io/ in there you will see your api limit
