### ISSUE TITLE
Cannot communicate with {servicename} 

### ISSUE THREAD

**Issue by mvelebit** [leviathan-framework/leviathan#14]
I keep getting this error on every service whilst running the scans, any clues?

**Comment by utkusen** [comment]
Hello, Did you enter your Shodan, Censys API keys correctly?

**Comment by mvelebit** [comment]
I have entered my Shodan key, but not my Censys key. Still, Shodan doesn't work either. :(

**Comment by utkusen** [comment]
Could you please login to your Shodan account and check your API limit from their website?

**Comment by mvelebit** [comment]
My bad, I've left out a character from my API key. Sorry and thanks for your quick response.

**Comment by utkusen** [comment]
no problem
