### ISSUE TITLE
error on web scan for sqli 

### ISSUE THREAD

**Issue by doxsec** [leviathan-framework/leviathan#3]
Extracting URLs from Google for following dork: inurl:.php?id= inurl:gov,edu,com.gh
Link extraction failed! Probably your API limit exceeded
('Error on line 25', <class 'httplib2.SSLHandshakeError'>, SSLHandshakeError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))

**Comment by utkusen** [comment]
What is your Python version and operating system?

**Comment by doxsec** [comment]
i have python 2.7 installed and i am running kali linux

**Comment by doxsec** [comment]
i just got another error 


>>rdp
Extracting IPs for following query: country:us port:3389
Please wait..
Cannot communicate with Shodan.io

**Comment by utkusen** [comment]
I'm trying to reproduce the first issue. For second issue, did you put your shodan key? If yes please restart the program and try again.

**Comment by doxsec** [comment]
ok so have u been able to solve the 1st issue?

**Comment by Bobbydigitale** [comment]
I have the same error

Extracting IPs for following query: country:ca port:21
Please wait..
Cannot communicate with Shodan.io

I have put my API

**Comment by utkusen** [comment]
@Bobbydigitale did you restart the program after you put your API key?

**Comment by Bobbydigitale** [comment]
Yes i do

**Comment by utkusen** [comment]
@Bobbydigitale could you please check your shodan api limit? login to your account at shodan.io, navigate to: https://account.shodan.io/ in there you will see your api limit

**Comment by Bobbydigitale** [comment]
I have reboot machine still say : Please wait..
Cannot communicate with Shodan.io

**Comment by utkusen** [comment]
@Bobbydigitale did you check your api limit on shodan?

**Comment by Bobbydigitale** [comment]
dO I HAVE AN LIMIT?

**Comment by utkusen** [comment]
@Bobbydigitale of course you have

**Comment by Bobbydigitale** [comment]
Hello!

Thanks very much for your email and new order! Please kindly find the
attached  Invoice and confirm!

Please note:

1. Shipment date: around Aug. 4th is OK? And the L/C to show lastest day of
shipment: Aug. 10, 2017 is OK for you?

2. Half L/C charge is about USD 72, can we share this charge on Item
YT3612-A, each will add USD 0.12, now unit price change to USD 8.92 is that
OK?

Best regards,

**Comment by bounce18** [comment]
Link extraction failed! Probably your API limit exceeded
i am getting the error plz help me

**Comment by utkusen** [comment]
@bounce18 please check your Google key

**Comment by Bobbydigitale** [comment]
Hello:
Order ID: 81557
Date Ordered: 22/08/2017

Your order has been updated to the following status:
Complete

To view your order click on the link below:
https://drive.google.com/open?id=0Bwn_x42TR12edk9CQVdtZXo3b28
