### ISSUE TITLE
Error  "Cannot communicate with ..." Shodan and Censys

### ISSUE THREAD

**Issue by MarieUwU-nerd** [leviathan-framework/leviathan#5]
```
    Enter Country Code:

    (Examples:TR,RU,USA,IT)
    
>>FR

    Enter Protocol 

    (Examples:ssh, ftp, telnet, smb, rdp, mysql):
    
>>ssh
Extracting IPs for following query: country:FR port:22
Please wait..
Cannot communicate with Shodan.io
```

**Comment by utkusen** [comment]
you entered your API keys right?

**Comment by evilcode1** [comment]
same error here

**Comment by utkusen** [comment]
did you guys entered your API keys correctly?

**Comment by evilcode1** [comment]
yes

**Comment by utkusen** [comment]
Alright I also got the error. I will fix it soon

**Comment by utkusen** [comment]
The problem is solved when I enter my api key, quit the program and try again. When the first time you enter the api key, leviathan can't read that change since `leviathan_config.py` file is already opened. Could you please try again?

**Comment by MarieUwU-nerd** [comment]
I tryed and still have the error and yes i put my api

**Comment by utkusen** [comment]
I couldn't reproduce the issue. If exit, reopen is not worked for you, please make sure that your API key has limit.
