### ISSUE TITLE
No module named shodan

### ISSUE THREAD

**Issue by Nomed1478963** [leviathan-framework/leviathan#9]
Traceback (most recent call last):
  File "leviathan.py", line 20, in <module>
    from lib.protocol_scanner import shodan_search, censys_search, mass_scan
  File "/root/leviathan/lib/protocol_scanner.py", line 7, in <module>
    import shodan
ImportError: No module named shodan

and i m sure that shodan is installed

**Comment by utkusen** [comment]
what is your operating system?

also could you please run `pip install shodan` and paste the output to here?

**Comment by Nomed1478963** [comment]
my operating system is kali 2017.1

the output of pip install 

:~# pip install shodan
Requirement already satisfied: shodan in /usr/local/lib/python3.5/dist-packages/shodan-1.6.5-py3.5.egg
Requirement already satisfied: simplejson in /usr/local/lib/python3.5/dist-packages (from shodan)
Requirement already satisfied: requests>=2.2.1 in /usr/local/lib/python3.5/dist-packages (from shodan)
Requirement already satisfied: click in /usr/local/lib/python3.5/dist-packages (from shodan)
Requirement already satisfied: click-plugins in /usr/local/lib/python3.5/dist-packages (from shodan)
Requirement already satisfied: colorama in /usr/local/lib/python3.5/dist-packages (from shodan)

**Comment by utkusen** [comment]
it seems your default pip points to python 3. Could you please run following command `pip2 install -r requirements.txt`
